Nanoscan3 description folder
SICKAG/sick_safetyscanners2 pull request #37
Opened 2024-02-26 10:42 UTC by Nibanovic

Added the nanoscan3 description folder. Features:
- visual and collision meshes
- `mounting_kit` conditional, which specifies whether to load the sensor with [SICK Mounting Kit 2a](https://www.sick.com/at/en/catalog/accessories/mounting-systems/mounting-kit-2a/p/p654159)
- `XML` and `python` launch files for viewing the sensor

### To try it out:
```
colcon build
ros2 launch sick_safetyscanners2 view_nanoscan3.launch.<py/xml> mounting_kit:=<true/false>
```

2024-02-28 15:44 UTC, destogl requested changes
Few initial comments.

Can you also add Gazebo support, please, the same as in another repository?

2024-02-28 15:44 UTC, destogl commented on description/meshes/nanoscan3/collision/mount.dae
Regading collisions and visuals, we should follow the structure that is in `sick_scan` package. Also can you add collision meshes as `.stl` files and simplify them with a convex hull tool. This makes it easier for collitions checker to calculate colliions in real-time.

2024-02-28 15:44 UTC, destogl commented on README.md
We can remove this file.

2024-02-28 15:44 UTC, destogl commented on description/urdf/nanoscan3.urdf.xacro
> +  <xacro:arg name="simulation_controllers" default="" />
We don't need this filed here. Please also remove on other places.

```suggestion
  <xacro:arg name="sim_gazebo" default="false" />
```

2024-02-28 15:44 UTC, destogl commented on description/urdf/nanoscan3.urdf.xacro
> +    simulation_controllers="$(arg simulation_controllers)" />
There is currently not ros2_control support for such sensors.

2024-02-28 15:44 UTC, destogl commented on description/urdf/nanoscan3/nanoscan3_macro.ros2_control.xacro
we can delete this.

2024-02-28 15:44 UTC, destogl commented on description/urdf/nanoscan3/nanoscan3_macro.xacro
> +  <xacro:macro name="nanoscan3" params="prefix name parent *origin mounting_kit">
If we can set the name, then we don't need to prefix. This is then duplicated and reduces understanding.

```suggestion
  <xacro:macro name="nanoscan3" params="name parent *origin mounting_kit">
```

2024-02-28 15:44 UTC, destogl commented on description/urdf/nanoscan3/nanoscan3_macro.xacro
> +          <xacro:insert_block name="origin" />
This will move visual to the wrong position. Basically, double movement. 

```suggestion
          <origin xyz="0 0 0" rpy="0 0 0" />
```

2024-02-28 15:44 UTC, destogl commented on description/urdf/nanoscan3/nanoscan3_macro.xacro
> +          <xacro:insert_block name="origin" />
This will move collision to the wrong position. Basically, double movement. 

```suggestion
          <origin xyz="0 0 0" rpy="0 0 0" />
```

2024-03-01 11:06 UTC, Nibanovic commented
> Can you also add Gazebo support, please, the same as in another repository?

Can you elaborate on this? The same as which other repository?

2024-03-01 12:00 UTC, destogl commented
When you start another task, check my changes in this package *commited and not commited. After they you will see how I have added gazebo support. I was ortienting myself to the sick_scan_xd repository.

2024-03-04 08:07 UTC, destogl commented on package.xml
> +  <exec_depend>joint_state_publisher_gui</exec_depend>
We don't have any joints here, so this is not necessary
```suggestion
```

2024-03-05 08:49 UTC, destogl approved these changes
Thanks!

2024-03-05 08:50 UTC, destogl commented
@padhupradheep and @neobotix do you find this helpful regarding #35?

2024-03-05 09:49 UTC, padhupradheep commented
Great work! looks good to me..

2024-04-03 08:08 UTC, puck-fzi commented
Thanks for bringing this up, and thanks for the detailed review.

2024-04-03 08:17 UTC, merged